version: '3'

services:
  mc:
    image: openjdk
    container_name: mc
    ports:
      - 25565:25565
    working_dir: /app
    volumes:
      - ./:/app
    command: java -Xmx1024M -Xms1024M -jar /app/server.jar nogui
